miniblog-master/blogpost/blogging/urls.py
from django.urls import path
from . import views
urlpatterns = [

        path('',views.home,name='home'),
        path('sign_up/',views.registration,name ='sign_up' ),
        path('about/',views.about,name ='about' ),
        path('sign_in/',views.sign_in,name ='sign_in' ),
        path('dashboard/',views.dashboard,name ='dashboard' ),
        path('logout/',views.user_logout,name ='logout' ),
        path('addpost/',views.addpost,name ='addpost' ),
        path('updatepost/<int:id>/',views.updatepost,name ='updatepost' ),
        path('deletepost/<int:id>/',views.deletepost,name ='deletepost' ),
        path('contact/',views.contact_us,name ='contact' ),
        path('article/<int:id>/',views.read_article,name ='article' ),

]

miniblog-master/blogpost/blogpost/urls.py
from django.contrib import admin
from django.urls import path,include
import blogging
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogging.urls')),
]

miniblog-master/blogpost/blogging/models.py
from django.db import models

class Post(models.Model):
    title  = models.CharField(max_length=70)
    desc = models.TextField()

miniblog-master/blogpost/blogging/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django import forms
from .models import Post

class PersonRegistration(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Enter Password(again)',widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model=User
        fields = ['username','first_name','last_name','email']
        labels = {'username':'Enter UserName','first_name':'Enter First Name','last_name':'Enter Last Name','email':'Enter Email'}
        widgets = {'username':forms.TextInput(attrs={'class':'form-control'}),'first_name':forms.TextInput(attrs={'class':'form-control'}),'last_name':forms.TextInput(attrs={'class':'form-control'}),'email':forms.EmailInput(attrs={'class':'form-control'})}


class PersonLogin(AuthenticationForm):
   username = UsernameField(widget=forms.TextInput(attrs={'autofocus':True,'class':'form-control'}))
   password = forms.CharField(label='Password', strip = False,widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))

class PostCreate(forms.ModelForm):
    class Meta:
        model=Post
        fields = ['title','desc']
        labels = {'title':'Title','desc':'Description'}
        widgets = {'title':forms.TextInput(attrs={'class':'form-control'}),'desc':forms.Textarea(attrs={'class':'form-control'})}



class Contactform(forms.Form):
     name = forms.CharField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
     email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-control'}))
     query = forms.CharField(label='Ask Question', widget=forms.Textarea(attrs={'class': 'form-control'}))

miniblog-master/blogpost/blogging/views.py
from django.shortcuts import render,HttpResponseRedirect,HttpResponse,redirect
from .forms import PersonRegistration,PersonLogin,PostCreate,Contactform
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import Group
from .models import Post
from django.contrib import messages
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.core.cache import cache
# Home
def home(request):
     post = Post.objects.all()
     return render(request,'blogging/home.html',{'posts':post})
# Registration
def registration(request):
     if not request.user.is_authenticated:
        if request.method=='POST':
            fm = PersonRegistration(request.POST)
            if fm.is_valid():
                 user = fm.save()
                 group = Group.objects.get(name='User')
                 user.groups.add(group)
                 messages.success(request,'You are registerd successfully')
        else :  fm = PersonRegistration()
        return render(request,'blogging/registration.html',{'forms':fm})
     else:
         return HttpResponseRedirect('/dashboard/')
# ḷogin
def sign_in(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            fm = PersonLogin(request=request,data= request.POST)
            if fm.is_valid():
                username = fm.cleaned_data['username']
                password = fm.cleaned_data['password']
                user = authenticate(username=username,password=password)
                if user is not None:
                    login(request,user)
                    return HttpResponseRedirect('/dashboard/')
        
        else :
            fm = PersonLogin()
        return render(request,'blogging/login.html',{'forms':fm})
    else :
        return HttpResponseRedirect('/dashboard/')

# logout
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/sign_in/')

# dashboard
def dashboard(request):
    if request.user.is_authenticated:
        post = Post.objects.all()
        user = request.user
        full_name = user.get_full_name()
        gps = user.groups.all()
        ip = request.session.get('ip',0)
        ch = cache.get('count',version=user.pk)

        return render(request,'blogging/dashboard.html',{'posts':post,'full_name':full_name,'groups':gps,'ip':ip,'ch':ch})

    else :
       return  HttpResponseRedirect('/sign_in/')


# About Section
def about(request):
    return render(request,'blogging/about.html')

    # Adding a PostCreate
def addpost(request):
     
      if request.method=='POST':
            fm = PostCreate(request.POST)
            if fm.is_valid():
                fm.save()
                messages.success(request,'Congartulations! Article is Published. Click on cancle for go back to home')
      else :  fm = PostCreate()
      return render(request,'blogging/addpost.html',{'forms':fm})

def updatepost(request,id):     
      if request.method=='POST':
            pi = Post.objects.get(pk=id)
            fm = PostCreate(request.POST,instance=pi)
            if fm.is_valid():
                title = fm.cleaned_data['title']
                desc = fm.cleaned_data['desc']
                user = Post(id=id,title=title,desc=desc)
                user.save()
                messages.success(request,'Article is Updated Successfully')
                        
      else : 
          pi = Post.objects.get(pk=id)
          fm = PostCreate(instance=pi)
      return render(request,'blogging/updatepost.html',{'forms':fm})
def deletepost(request,id):  
    if request.method=='POST':
            fm = Post.objects.get(pk=id)
            fm.delete()

def read_article(request,id):
    post = Post.objects.get(pk=id)
    return render(request,'blogging/article.html',{'posts':post})

def contact_us(request):
    if request.method=='POST':
        fm = Contactform(request.POST)
        if fm.is_valid():
            name  = fm.cleaned_data['name']
            email_from  =settings.EMAIL_HOST_USER
            query  = fm.cleaned_data['query']
            recipient_list= ['abhishekudiya2000@gmail.com',]
            try:
                send_mail('User wants to contact', query, email_from, recipient_list,fail_silently=False)
                messages.success(request, f'Thank you {name} for contacting us. We will reach out to you as soon as possible.')
            except Exception as e:
                messages.error(request, 'An error occurred while sending the email. Please try again later.')

            return redirect('/contact/')
    else : fm = Contactform()
    return  render(request,'blogging/contact.html',{'forms':fm})

miniblog-master/blogpost/blogging/templates/blogging/about.html
{% extends 'blogging/base.html' %} {% block title %} Home {% endblock title %}
{% block content %}
<div class="col-sm-12 mt-5">
    <h3 class="text-white mb-4">About Page</h3>
  <p class="lead">

    Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam tenetur
    explicabo harum, quisquam atque officia sequi molestiae neque sit commodi
    porro iure dolor consequatur aut totam dolores odit. Delectus facilis veniam
    nobis officia laudantium, ratione totam neque eos? Nemo, praesentium quia.
    Dolorum culpa ullam deleniti, a nemo explicabo assumenda perspiciatis
    quaerat illo exercitationem provident sequi nostrum ipsam incidunt! Veniam
    ad eligendi a. Autem aperiam quaerat, itaque soluta culpa aut iusto nisi
    architecto atque, beatae quod quia reprehenderit sapiente explicabo odit,
    tempore non quibusdam? Libero fugiat quod earum laudantium, eligendi,
    obcaecati laboriosam laborum ratione nesciunt eius harum corporis ipsam
    placeat exercitationem pariatur quas. Illum vitae a dolores excepturi
    cupiditate recusandae doloribus deleniti asperiores esse sequi. Corporis
    obcaecati perspiciatis est corrupti illo dolor maxime a non quae! Tempora
    sed eligendi quisquam, necessitatibus ipsum totam architecto? Quis
    consectetur odit assumenda placeat tenetur quod mollitia fugit accusamus
    soluta inventore, modi nostrum deleniti. Placeat culpa animi odit porro
    numquam. Corporis ab laborum nemo tempora at perspiciatis tempore rem
    aperiam? Obcaecati deserunt distinctio est aspernatur alias quo quibusdam
    hic, voluptatem, autem officia quae quia reiciendis. Voluptas accusantium
    dignissimos laborum soluta a quos ratione eaque odit est quae sapiente
    asperiores sequi nihil, architecto quisquam magni maxime ad consequatur
    necessitatibus. Error dignissimos facilis officiis veniam dicta voluptate
    molestiae, placeat tempora, iusto maxime et sequi ipsam consequuntur
    sapiente amet tenetur? Hic quam quia quod quaerat. Placeat in dolorem optio
    omnis saepe quos cum molestias autem debitis corrupti veritatis mollitia,
    voluptatem inventore fugit explicabo ut eveniet fugiat maxime deserunt
    asperiores quaerat necessitatibus recusandae quam. Numquam recusandae, quam
    aut inventore, nostrum delectus omnis molestiae cum quos sint sequi dolore.
    Ut eligendi possimus vero laboriosam minima consectetur est voluptates alias
    doloribus, veniam facilis suscipit delectus tenetur natus at aperiam, quae
    rerum incidunt hic. Similique assumenda dignissimos ad architecto illum
    accusamus. Vero, modi!
  </p>
  {% endblock content %}
</div>

miniblog-master/blogpost/blogging/templates/blogging/addpost.html
{% extends 'blogging/base.html' %}
{% block title %} Register {% endblock %} 

{% block content %}

<div class="col-sm-10">
 <h3 class="text-white my-5">Write Blog</h3> 
 <form action="" method="post" novalidate>
  {% csrf_token %}
  {% if messages %} 
  {% for message in messages %}
   <h3 class="alert alert-{{ message.tags }}">{{ message }}</h3>
   {% endfor %}
{% endif %}
  {% for fm in forms %}
   <div class="form-group">
   <p>{{fm.label_tag}} {{fm}}</p>  <small class="text-warning">{{fm.errors|striptags}}</small>
   </div>
  {% endfor %}
  <input type="submit" value="Add" class="btn btn-danger">
  <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
  {% if form.non_field_errors %}
   {% for error in form.non_field_errors %}
    <p class="alert alert-danger my-3">{{error}}</p>
   {% endfor %}
  {% endif %}
 </form>
</div>

{% endblock content %}

miniblog-master/blogpost/blogging/templates/blogging/article.html
{% extends 'blogging/base.html' %}
 {% block title %} Home {% endblock title %}
{% block content %}
<div class="col-sm-12 mt-5">
  <h3 class="text-white mb-4">Full Page</h3>
  <div class="jumbotron jumbotron-fluid jombo-color m-5">
      <div class="container p-3">
      <h1 class="fw-bold font-weight-bold">{{posts.title}} </h1>
      <p class="lead">
       {{posts.desc}}
      </p>
    </div>
</div>
</div>

{% endblock content %}

miniblog-master/blogpost/blogging/templates/blogging/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blogging/css/style.css' %}">
</head>
<body>
    <!-- nav bar -->    
    <div class="container-fluid bg-dark">
      {% include 'blogging/navbar.html' %}
     </div>

     <div class="container mt-5">
      <div class="row">
       <div class="col-sm-12">
        {% block msg %}
        {% endblock msg %}
       </div>
      </div>
    
      <div class="row text-white">
       {% block side %}
       {% endblock side %}
    
       {% block content %}
       {% endblock content %}
      </div>
     </div>
    









   <script src="{% static 'blogging/js/bootstrap.min.js' %}"></script>
   <script src="{% static 'blogging/js/popper.js' %}"></script>
   <script src="{% static 'blogging/js/jquery.js' %}"></script>
</body>
</html>

miniblog-master/blogpost/blogging/templates/blogging/contact.html
{% extends 'blogging/base.html' %}
{% block title %} Register {% endblock %} 

{% block content %}

<div class="col-sm-10">
 <h3 class="text-white my-5">Contact Us</h3> 
 <form action="" method="post" novalidate>
  {% csrf_token %}
  {% if messages %} 
  {% for message in messages %}
   <h3 class="alert alert-{{ message.tags }}">{{ message }}</h3>
   {% endfor %}
{% endif %}
  {% for fm in forms %}
   <div class="form-group">
   <p>{{fm.label_tag}} {{fm}}</p>  <small class="text-warning">{{fm.errors|striptags}}</small>
   </div>
  {% endfor %}
  <input type="submit" value="Submit" class="btn btn-primary">
  {% if form.non_field_errors %}
   {% for error in form.non_field_errors %}
    <p class="alert alert-danger my-3">{{error}}</p>
   {% endfor %}
  {% endif %}
 </form>
</div>

{% endblock content %}

miniblog-master/blogpost/blogging/templates/blogging/dashboard.html
{% extends 'blogging/base.html' %}
{% block title %} Register {% endblock %} 

{% block side %}

<div class="col-sm-2 my-5 text-center">
<h4 class="my-5">Profile</h4>
<h4>{{full_name}}</h4>
{% for group in groups %}
    <p>{{group.name}}</p>
{% endfor %}
<button type="button" class="btn btn-secondary">
  IP : <span class="badge">{{ip}}</span>
</button>
<button type="button" class="btn btn-primary mt-3">
  Login Times : <span class="badge bg-danger">{{ch}}</span>
</button>
</div>

{% endblock side %}


{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard Page</h3> 
    <a href="{% url 'addpost' %}" class="btn btn-success">Add Post</a>
    <h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
    {% if posts %}
    <table class="table table-hover bg-white">
      <thead>
        <tr class="text-center">
          <th scope="col" style="width:2%">ID</th>
          <th scope="col" style="width:28%">Title</th>
          <th scope="col" style="width:55%">Description</th>
          <th scope="col" style="width:15%">Action</th>
        </tr>
      </thead>
      <tbody>
       {% for post in posts %}
        <tr>
          <th scope="row">{{post.id}}</th>
          <td>{{post.title}}</td>
          <td> <div class="text-truncate" style="max-width: 600px;">{{post.desc}}</div>
          </td>
          <td class="text-center">
           <a href="{% url 'updatepost' post.id %}" class="btn btn-warning btn-sm">Edit</a>
           {% if perms.blogging.delete_post %}
           <form action="{% url 'deletepost' post.id %}" method="post" class="d-inline"> {% csrf_token %}
           <input type="submit" class="btn btn-danger btn-sm" value="Delete">
          </form>
          {% endif %}
          </td>
        </tr>
       {% endfor %}
      </tbody>
    </table>
 
   {% else %}
    <h4 class="text-center alert alert-warning">No Records</h4>
   {% endif %}
 </div>
{% endblock content %}

miniblog-master/blogpost/blogging/templates/blogging/home.html
{% extends 'blogging/base.html' %}
 {% block title %} Home {% endblock title %}
{% block content %}
<div class="col-sm-10 mt-5">
  <h3 class="text-white mb-4">Home Page</h3>

  {% for post in posts %}
  <div class="jumbotron jumbotron-fluid jombo-color m-5">
      <div class="container p-3">
      <h1 class="fw-bold font-weight-bold">{{post.title}} </h1>
      <p class="lead text-truncate">
       {{post.desc}}
      </p>
      <a href="{% url 'article' post.id %}" class="btn btn-danger">Explore More</a>
    </div>
</div>
{% endfor %}
</div>

{% endblock content %}

miniblog-master/blogpost/blogging/templates/blogging/login.html
{% extends 'blogging/base.html' %}
{% block title %} Register {% endblock %} 

{% block content %}

<div class="col-sm-10">
 <h3 class="text-white my-5">Login Author</h3> 
 <form action="" method="post" novalidate>
  {% csrf_token %}
  {% for fm in forms %}
   <div class="form-group">
   <p>{{fm.label_tag}} {{fm}}</p>  <small class="text-warning">{{fm.errors|striptags}}</small>
   </div>
  {% endfor %}
  <input type="submit" value="Submit" class="btn btn-primary">
  {% if form.non_field_errors %}
   {% for error in form.non_field_errors %}
    <p class="alert alert-danger my-3">{{error}}</p>
   {% endfor %}
  {% endif %}
 </form>
</div>

{% endblock content %}

miniblog-master/blogpost/blogging/templates/blogging/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark fixed-top">
    <div class="container">
      <a href="{% url 'home' %}" class="navbar-brand"> Mini Blog</a>

      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navmenu"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navmenu">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a href="{% url 'home' %}" class="nav-link">Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'about' %}"  class="nav-link">About </a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'dashboard' %}"   class="nav-link">Dashboard </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a href="{% url 'contact' %}"  class="nav-link">Contact </a>
          </li>
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'sign_in' %}"  class="nav-link">Sign_in </a>
          </li>
          {% endif %}
          {% if not request.user.is_authenticated %}
          <li class="nav-item">
              <a href="{% url 'sign_up' %}" class="nav-link">Sign_up </a>
            </li>
            {% endif %}
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'logout' %}"  class="nav-link">Logout </a>
            </li>
            {% endif %}
        </ul>
      </div>
    </div>
  </nav>

miniblog-master/blogpost/blogging/templates/blogging/registration.html
{% extends 'blogging/base.html' %}
{% block title %} Register {% endblock %} 

{% block content %}

<div class="col-sm-10">
 <h3 class="text-white my-5">Become an Author</h3> 
 <form action="" method="post" novalidate>
  {% csrf_token %}
  {% if messages %} 
  {% for message in messages %}
   <h3 class="alert alert-{{ message.tags }}">{{ message }}</h3>
   {% endfor %}
{% endif %}
  {% for fm in forms %}
   <div class="form-group">
   <p>{{fm.label_tag}} {{fm}}</p>  <small class="text-warning">{{fm.errors|striptags}}</small>
   </div>
  {% endfor %}
  <input type="submit" value="Submit" class="btn btn-primary">
  {% if form.non_field_errors %}
   {% for error in form.non_field_errors %}
    <p class="alert alert-danger my-3">{{error}}</p>
   {% endfor %}
  {% endif %}
 </form>
</div>

{% endblock content %}

miniblog-master/blogpost/blogging/templates/blogging/updatepost.html
{% extends 'blogging/base.html' %}
{% block title %} Register {% endblock %} 

{% block content %}

<div class="col-sm-10">
 <h3 class="text-white my-5">Update Blog</h3> 
 <form action="" method="post" novalidate>
  {% csrf_token %}
  {% if messages %} 
  {% for message in messages %}
   <h3 class="alert alert-{{ message.tags }}">{{ message }}</h3>
   {% endfor %}
{% endif %}
  {% for fm in forms %}
   <div class="form-group">
   <p>{{fm.label_tag}} {{fm}}</p>  <small class="text-warning">{{fm.errors|striptags}}</small>
   </div>
  {% endfor %}
  <input type="submit" value="Update" class="btn btn-danger">
  <a href="{% url 'dashboard' %}" class="btn btn-danger">Cancel</a>
  {% if form.non_field_errors %}
   {% for error in form.non_field_errors %}
    <p class="alert alert-danger my-3">{{error}}</p>
   {% endfor %}
  {% endif %}
 </form>
</div>

{% endblock content %}